#ifndef CONSTANTS_H
#define CONSTANTS_H

static const char* MAIN_PAGE =
"<!DOCTYPE html>"
"<html lang='ru'>"
"<head>"
"  <meta charset='UTF-8'>"
"  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"  <title>Калькулятор времени</title>"
"  <link rel='stylesheet' href='/css/styles.css'>"
"</head>"
"<body>"
"  <div class='container'>"
"    <h1>Калькулятор времени в пути</h1>"
"    <form method='POST' action='/calculate'>"
"      <div class='form-group'>"
"        <label for='distance'>Расстояние (км):</label>"
"        <input type='number' id='distance' name='distance' step='0.1' min='0.1' required>"
"      </div>"
"      <div class='form-group'>"
"        <label for='speed'>Средняя скорость (км/ч):</label>"
"        <input type='number' id='speed' name='speed' step='1' min='1' required>"
"      </div>"
"      <button type='submit'>Рассчитать</button>"
"    </form>"
"  </div>"
"</body>"
"</html>";

static const char* RESULT_TEMPLATE =
"<!DOCTYPE html>"
"<html lang='ru'>"
"<head>"
"  <meta charset='UTF-8'>"
"  <title>Результат</title>"
"  <link rel='stylesheet' href='/css/styles.css'>"
"</head>"
"<body>"
"  <div class='container'>"
"    <h1>Результат расчёта</h1>"
"    <div class='result-box'>"
"      <p>Время в пути: <strong>%d часов %d минут</strong></p>"
"      <p>Расстояние: %.1f км, Скорость: %.1f км/ч</p>"
"    </div>"
"    <a href='/' class='btn'>Новый расчёт</a>"
"  </div>"
"</body>"
"</html>";

static const char* ERROR_PAGE =
"<!DOCTYPE html>"
"<html lang='ru'>"
"<head>"
"  <meta charset='UTF-8'>"
"  <title>Ошибка</title>"
"  <link rel='stylesheet' href='/css/styles.css'>"
"</head>"
"<body>"
"  <div class='container'>"
"    <h1>Ошибка</h1>"
"    <div class='error'>"
"      <p>Некорректные данные! Введите положительные числа.</p>"
"      <a href='/' class='btn'>Назад</a>"
"    </div>"
"  </div>"
"</body>"
"</html>";

static const char* NOT_FOUND_PAGE =
"<!DOCTYPE html>"
"<html lang='ru'>"
"<head>"
"  <meta charset='UTF-8'>"
"  <title>404</title>"
"  <link rel='stylesheet' href='/css/styles.css'>"
"</head>"
"<body>"
"  <div class='container'>"
"    <h1>Страница не найдена</h1>"
"    <a href='/' class='btn'>На главную</a>"
"  </div>"
"</body>"
"</html>";

#endif
