#ifndef CONSTANTS_H
#define CONSTANTS_H
static const char* MAIN_PAGE =
"<!DOCTYPE html>"
"<html lang='ru'>"
"<head>"
"  <meta charset='UTF-8'>"
"  <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"  <title>Калькулятор времени</title>"
"  <link rel='stylesheet' href='/css/styles.css'>"
"  <script>"
"    function toggleTheme() {"
"      document.body.classList.toggle('dark-theme');"
"      localStorage.setItem('theme', document.body.classList.contains('dark-theme') ? 'dark' : 'light');"
"    }"
"    document.addEventListener('DOMContentLoaded', () => {"
"      if (localStorage.getItem('theme') === 'dark') document.body.classList.add('dark-theme');"
"    });"
"  </script>"
"</head>"
"<body>"
"  <div class='container'>"
"    <h1>Калькулятор времени в пути</h1>"
"    <form method='POST' action='/calculate'>"
"      <div class='form-group'>"
"        <label for='distance'>Расстояние (км):</label>"
"        <input type='number' id='distance' name='distance' step='0.1' min='0.1' required>"
"      </div>"
"      <div class='form-group'>"
"        <label for='speed'>Средняя скорость (км/ч):</label>"
"        <input type='number' id='speed' name='speed' step='1' min='1' required>"
"      </div>"
"      <button type='submit'>Рассчитать</button>"
"    </form>"
"  </div>"
"  <footer>"
"    <p class='signature'>Выполнил: Семейкин Михаил ПВ-242</p>"
"  </footer>"
"</body>"
"</html>";
static const char* RESULT_TEMPLATE =
"<!DOCTYPE html>"
"<html lang='ru'>"
"<head>"
"  <meta charset='UTF-8'>"
"  <title>Результат</title>"
"  <link rel='stylesheet' href='/css/styles.css'>"
"</head>"
"<body>"
"  <div class='container'>"
"    <h1>Результат расчёта</h1>"
"    <div class='result-box'>"
"      <p>Время в пути: <strong>%d часов %d минут</strong></p>"
"      <p>Расстояние: %.1f км, Скорость: %.1f км/ч</p>"
"    </div>"
"    <a href='/' class='btn'>Новый расчёт</a>"
"  </div>"
"</body>"
"</html>";

static const char* ERROR_PAGE =
"<!DOCTYPE html>"
"<html lang='ru'>"
"<head>"
"  <meta charset='UTF-8'>"
"  <title>Ошибка</title>"
"  <link rel='stylesheet' href='/css/styles.css'>"
"</head>"
"<body>"
"  <div class='container'>"
"    <h1>Ошибка</h1>"
"    <div class='error'>"
"      <p>Некорректные данные! Введите положительные числа.</p>"
"      <a href='/' class='btn'>Назад</a>"
"    </div>"
"  </div>"
"</body>"
"</html>";
#endif
